# GitHub Pages Configuration for TUIZ Documentation

# Site settings
title: "TUIZ Documentation"
description: "Real-time Quiz Application Documentation"
url: "https://pandadev0069.github.io"
baseurl: "/TUIZ"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - README.md
  - BUG_TRACKER.md
  - TODO.md
  - ROADMAP.md
  - FEATURE_REQUESTS.md
  - DEVELOPMENT_GUIDE.md

# Exclude files from processing
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - archive/
  - "*.log"
  - "ADVANCED_SCORING_SYSTEM_SUMMARY.md"
  - "Day2_MemoryLeak_Implementation_Summary.md"
  - "EXPLANATION_LEADERBOARD_CLEANUP_PLAN.md"
  - "IMPLEMENTATION_AUDIT_AND_FOLLOWUP_PLAN.md"
  - "PostQuestionDisplay_Implementation_Complete.md"
  - "Prompt_and_WorkFlow.md"
  - "QUIZ_DEVELOPMENT_ROADMAP.md"
  - "TODO's.md"
  - "UnifiedPostQuestion_Complexity_Audit.md"
  - "cleanup-summary.md"
  - "feature_req.md"
  - "game-settings-fix-summary.md"
  - "host_lobby_settings_guide.md"
  - "plan.md"

# Include files
include:
  - _pages

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# SEO settings
author:
  name: "PandaDev0069"
  
twitter:
  username: pandadev0069
  
social:
  name: PandaDev0069
  links:
    - https://github.com/PandaDev0069
